In [1]:
import numpy as np
import pandas as pd
from IPython.display import display

In [2]:
data_input = pd.read_excel('E:/Graduate_Project/IEEE ISI World Cup 2019/competition1/test/一般纳税人.xlsx')
display(data_input.head())

,企业编号,纳税人资格,认定日期,有效日期期起,有效截止日期,是否具有一般纳税人资格,纳税人状态,登记注册类型,扣缴义务,出口状态备案状态,是否按季申报
0,4001,一般纳税人,2001年04月30日,NaN,NaN,NaN,正常,非国有控股上市企业,依法确定,NaN,NaN
1,4002,一般纳税人,1995年01月26日,NaN,NaN,NaN,正常,非国有控股非上市企业,依法确定,NaN,NaN
2,4003,一般纳税人,NaN,2005-03-01,2099-12-31,NaN,NaN,NaN,NaN,NaN,NaN
3,4004,一般纳税人,2012-08-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4005,一般纳税人,2015-12-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
data = data_input.loc[:,['企业编号', '纳税人资格', '登记注册类型']]
# data = data.fillna(0)
data.head()

   企业编号  纳税人资格      登记注册类型
0  4001  一般纳税人   非国有控股上市企业
1  4002  一般纳税人  非国有控股非上市企业
2  4003  一般纳税人         NaN
3  4004  一般纳税人         NaN
4  4005  一般纳税人         NaN

In [4]:
data['登记注册类型'].isna().sum()
data.shape

(529, 3)

In [5]:
data.drop('登记注册类型', axis=1, inplace=True)

In [6]:
# data['登记注册类型'] = data['登记注册类型'].astype('category') #将列转换成category类型
# data['登记注册类型'].cat.categories = [i for i in range(20)] #将列转换成对应的类别，并补充在最后一列
data_feature = data['纳税人资格']
data_feature.head()

0    一般纳税人
1    一般纳税人
2    一般纳税人
3    一般纳税人
4    一般纳税人
Name: 纳税人资格, dtype: object

In [7]:
# data['纳税人资格'] = data['纳税人资格'].astype('category')
# data['纳税人资格'].cat.categories = [i for i in range(18)]
data_feature_dumm = pd.get_dummies(data_feature)

In [8]:
display(data_feature_dumm.head())

,一般纳税人,内资企业采购国产设备,出口退（免）税企业,增值税汇总纳税企业,外商投资企业,小规模纳税人,福利企业,经济实体（安置富余人员）,软件及集成电路生产企业,销售供出口货物企业,高新技术产业企业
0,1,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,0

In [23]:
# data.to_excel('E:/Graduate_Project/competition1/after/一般纳税人_特征.xlsx', index = False)

In [24]:
# import numpy as np
# features = np.array(data.drop('企业编号', axis=1))
# # features

In [25]:
# from sklearn.preprocessing import OneHotEncoder
# enc = OneHotEncoder(handle_unknown='ignore')
# enc.fit(features)
# # enc.categories_

OneHotEncoder(categorical_features=None, categories=None,
       dtype=<class 'numpy.float64'>, handle_unknown='ignore',
       n_values=None, sparse=True)

In [26]:
# features_n = enc.transform(features).toarray()
# features_n = pd.DataFrame(features_n, columns=enc.get_feature_names())
# data_output = pd.concat([data['企业编号'], features_n], axis=1)
# # data_output.head()

In [27]:
# data_output = data_output.groupby('企业编号').sum()
# data_output = data_output.reset_index()
# # data_output.head()

In [9]:
data_after = pd.concat([data, data_feature_dumm], axis=1)
data_after.head()

,企业编号,纳税人资格,一般纳税人,内资企业采购国产设备,出口退（免）税企业,增值税汇总纳税企业,外商投资企业,小规模纳税人,福利企业,经济实体（安置富余人员）,软件及集成电路生产企业,销售供出口货物企业,高新技术产业企业
0,4001,一般纳税人,1,0,0,0,0,0,0,0,0,0,0
1,4002,一般纳税人,1,0,0,0,0,0,0,0,0,0,0
2,4003,一般纳税人,1,0,0,0,0,0,0,0,0,0,0
3,4004,一般纳税人,1,0,0,0,0,0,0,0,0,0,0
4,4005,一般纳税人,1,0,0,0,0,0,0,0,0,0,0

In [10]:
data_after.drop(['纳税人资格', '福利企业'], axis=1, inplace=True)

In [12]:
data_output = pd.read_excel('E:\\Graduate_Project\\IEEE ISI World Cup 2019\\competition1\\赛题1结果_团队名.xlsx')
data_output = pd.merge(data_output, data_after, how='left')
data_output.head()
# data_output

,企业编号,一般纳税人,内资企业采购国产设备,出口退（免）税企业,增值税汇总纳税企业,外商投资企业,小规模纳税人,经济实体（安置富余人员）,软件及集成电路生产企业,销售供出口货物企业,高新技术产业企业
0,4001,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,4002,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,4003,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4003,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4004,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
data_output.fillna(0, inplace=True)
# data_output

In [14]:
data_output.drop_duplicates(inplace=True)
data_output

,企业编号,一般纳税人,内资企业采购国产设备,出口退（免）税企业,增值税汇总纳税企业,外商投资企业,小规模纳税人,经济实体（安置富余人员）,软件及集成电路生产企业,销售供出口货物企业,高新技术产业企业
0,4001,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,4002,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,4003,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4004,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4005,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,4005,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
7,4005,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
9,4006,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,4007,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,4008,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,4009,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,4009,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,4010,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,4010,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
17,4011,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,4012,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,4013,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,4014,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,4015,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,4016,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,4017,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,4018,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,4019,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,4020,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,4021,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,4022,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,4023,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,4024,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31,4025,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,4026,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
654,4501,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
655,4502,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
656,4503,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
657,4504,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
658,4505,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
659,4505,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
661,4506,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
662,4507,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
664,4508,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
665,4509,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
666,4510,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
667,4511,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
668,4512,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
669,4513,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
670,4514,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
671,4515,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
672,4516,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
673,4517,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
675,4518,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
677,4518,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
678,4518,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
679,4518,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
680,4519,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
681,4520,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
682,4521,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
683,4522,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
684,4523,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
685,4523,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
687,4524,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
688,4525,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [15]:
data_output = data_output.groupby('企业编号').sum()
data_output = data_output.reset_index()
data_output

,企业编号,一般纳税人,内资企业采购国产设备,出口退（免）税企业,增值税汇总纳税企业,外商投资企业,小规模纳税人,经济实体（安置富余人员）,软件及集成电路生产企业,销售供出口货物企业,高新技术产业企业
0,4001,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,4002,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,4003,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4004,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4005,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
5,4006,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,4007,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,4008,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,4009,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,4010,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
10,4011,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,4012,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,4013,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,4014,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,4015,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,4016,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,4017,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,4018,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,4019,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,4020,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,4021,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,4022,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,4023,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,4024,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,4025,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,4026,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,4027,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,4028,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,4029,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,4030,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
490,4496,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
491,4497,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
492,4498,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
493,4499,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
494,4500,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
495,4501,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
496,4502,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
497,4503,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
498,4504,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
499,4505,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
500,4506,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
501,4507,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
502,4508,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
503,4509,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
504,4510,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
505,4511,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
506,4512,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
507,4513,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
508,4514,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
509,4515,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
510,4516,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
511,4517,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
512,4518,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
513,4519,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
514,4520,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
515,4521,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
516,4522,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
517,4523,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
518,4524,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
519,4525,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [38]:
data_output = data_output.drop('企业总评分', axis=1)
data_output.head()

,企业编号,一般纳税人,其他,内资企业采购国产设备,出口退（免）税企业,增值税汇总纳税企业,外商投资企业,外资企业采购国产设备,小规模纳税人,有进出口经营权的外贸公司,消费税汇总纳税企业,经济实体（安置富余人员）,资源综合利用企业,软件及集成电路生产企业,金银首饰消费税纳税人,销售供出口货物企业,饲料产品企业,高新技术产业企业
0,1001,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1002,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1003,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1004,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1005,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
data_output.isna().sum()

企业编号            0
一般纳税人           0
内资企业采购国产设备      0
出口退（免）税企业       0
增值税汇总纳税企业       0
外商投资企业          0
小规模纳税人          0
经济实体（安置富余人员）    0
软件及集成电路生产企业     0
销售供出口货物企业       0
高新技术产业企业        0
dtype: int64

In [17]:
data_output.to_excel('一般纳税人_特征.xlsx', index=False)