In [1]:
import pandas as pd
import numpy as np
from IPython.display import display

In [2]:
data_input = pd.read_excel('E:\\Graduate_Project\\IEEE ISI World Cup 2019\\competition1\\test\\年报-企业基本信息.xlsx')
display(data_input.head())

,企业编号,注册资本,企业经营状态,从业人数,是否有网站或网点,企业是否有投资信息或购买其他公司股权,有限责任公司本年度是否发生股东股权转,是否提供对外担保,发布日期,年报年份
0,4001,NaN,开业,企业选择不公示,是,有,否,否,2015-06-04,2013
1,4001,NaN,开业,企业选择不公示,是,有,否,否,2015-06-04,2014
2,4001,NaN,开业,797人,是,有,否,否,2016-06-16,2015
3,4001,NaN,开业,企业选择不公示,是,有,否,否,2017-05-26,2016
4,4001,NaN,开业,企业选择不公示,是,有,否,否,2018-07-02,2017

In [3]:
data = data_input[['企业编号', '是否有网站或网点', '企业是否有投资信息或购买其他公司股权', 
                  '有限责任公司本年度是否发生股东股权转', '是否提供对外担保', '年报年份']]
data = data.dropna(how='any')
data = data[data['年报年份']==2017.0].reset_index(drop=True)
display(data)

     企业编号 是否有网站或网点 企业是否有投资信息或购买其他公司股权 有限责任公司本年度是否发生股东股权转 是否提供对外担保  年报年份
0    4001        是                  有                  否        否  2017
1    4002        是                  有                  否        否  2017
2    4003        是                  否                  否        否  2017
3    4004        是                  是                  否        否  2017
4    4005        是                  是                  否        否  2017
5    4006        是                  是                  否        否  2017
6    4007        是                  是                  否        否  2017
7    4003        是                  否                  否        否  2017
8    4008        是                  是                  否        否  2017
9    4009        是                  否                  否        否  2017
10   4010        是                  是                  否        否  2017
11   4011        是                  有                  否        否  2017
12   4012        否                  否                  否        否  2017
13   4013        是                  是                  否        否  2017
14   4014        是                  是                  否        否  2017
15   4015        是                  是                  否        否  2017
16   4016        是                  是                  否        否  2017
17   4017        是                  有                  否        否  2017
18   4018        是                  是                  否        否  2017
19   4019        否                  无                  否        否  2017
20   4020        是                  是                  否        否  2017
21   4021        是                  是                  否        否  2017
22   4022        是                  是                  否        否  2017
23   4023        是                  否                  是        否  2017
24   4024        是                  是                  否        否  2017
25   4025        否                  是                  否        否  2017
26   4026        是                  是                  否        否  2017
27   4027        是                  是                  是        否  2017
28   4028        是                  是                  否        否  2017
29   4029        是                  是                  否        否  2017
..    ...      ...                ...                ...      ...   ...
496  4496        否                  否                  否        否  2017
497  4497        是                  是                  否        否  2017
498  4498        是                  否                  否        否  2017
499  4499        是                  是                  否        否  2017
500  4500        是                  是                  否        否  2017
501  4501        是                  是                  否        否  2017
502  4502        是                  否                  否        否  2017
503  4503        否                  否                  否        否  2017
504  4504        是                  否                  否        否  2017
505  4505        是                  是                  否        否  2017
506  4506        是                  否                  否        否  2017
507  4507        是                  否                  否        否  2017
508  4508        否                  否                  否        否  2017
509  4509        是                  否                  否        否  2017
510  4510        是                  是                  否        否  2017
511  4511        是                  是                  否        否  2017
512  4512        是                  是                  否        否  2017
513  4513        是                  是                  否        否  2017
514  4514        否                  否                  否        否  2017
515  4515        否                  是                  否        否  2017
516  4516        是                  是                  否        否  2017
517  4517        有                  有                  无        否  2017
518  4518        否                  否                  否        否  2017
519  4519        是                  是                  否        否  2017
520  4520        是                  有                  否        否  2017
521  4521        否                  否                  否        否  2017
522  4522        是                  否                  否        否  2017
523  4523        是                  否                  是        否  2017
524  4524        是                  有                  否        否  2017
525  4525        否                  否                  否        否  2017

[526 rows x 6 columns]

In [4]:
data = data.replace({'是':1, '有':1, '否':0, '无':0})
# data.describe()

In [5]:
data.head()

   企业编号  是否有网站或网点  企业是否有投资信息或购买其他公司股权  有限责任公司本年度是否发生股东股权转  是否提供对外担保  年报年份
0  4001         1                   1                   0         0  2017
1  4002         1                   1                   0         0  2017
2  4003         1                   0                   0         0  2017
3  4004         1                   1                   0         0  2017
4  4005         1                   1                   0         0  2017

In [6]:
data.shape

(526, 6)

In [7]:
data.duplicated().sum()

3

In [8]:
data.drop_duplicates(inplace=True)
data.shape

(523, 6)

In [9]:
data1 = pd.read_excel('E:\\Graduate_Project\\IEEE ISI World Cup 2019\\competition1\\赛题1结果_团队名.xlsx')
# data1 = data1.drop('企业总评分', axis=1)
data_out = pd.merge(data1, data, how='left')
data_out

     企业编号  是否有网站或网点  企业是否有投资信息或购买其他公司股权  有限责任公司本年度是否发生股东股权转  是否提供对外担保  年报年份
0    4001         1                   1                   0         0  2017
1    4002         1                   1                   0         0  2017
2    4003         1                   0                   0         0  2017
3    4004         1                   1                   0         0  2017
4    4005         1                   1                   0         0  2017
5    4006         1                   1                   0         0  2017
6    4007         1                   1                   0         0  2017
7    4008         1                   1                   0         0  2017
8    4009         1                   0                   0         0  2017
9    4010         1                   1                   0         0  2017
10   4011         1                   1                   0         0  2017
11   4012         0                   0                   0         0  2017
12   4013         1                   1                   0         0  2017
13   4014         1                   1                   0         0  2017
14   4015         1                   1                   0         0  2017
15   4016         1                   1                   0         0  2017
16   4017         1                   1                   0         0  2017
17   4018         1                   1                   0         0  2017
18   4019         0                   0                   0         0  2017
19   4020         1                   1                   0         0  2017
20   4021         1                   1                   0         0  2017
21   4022         1                   1                   0         0  2017
22   4023         1                   0                   1         0  2017
23   4024         1                   1                   0         0  2017
24   4025         0                   1                   0         0  2017
25   4026         1                   1                   0         0  2017
26   4027         1                   1                   1         0  2017
27   4028         1                   1                   0         0  2017
28   4029         1                   1                   0         0  2017
29   4030         1                   0                   1         0  2017
..    ...       ...                 ...                 ...       ...   ...
490  4496         0                   0                   0         0  2017
491  4497         1                   1                   0         0  2017
492  4498         1                   0                   0         0  2017
493  4499         1                   1                   0         0  2017
494  4500         1                   1                   0         0  2017
495  4501         1                   1                   0         0  2017
496  4502         1                   0                   0         0  2017
497  4503         0                   0                   0         0  2017
498  4504         1                   0                   0         0  2017
499  4505         1                   1                   0         0  2017
500  4506         1                   0                   0         0  2017
501  4507         1                   0                   0         0  2017
502  4508         0                   0                   0         0  2017
503  4509         1                   0                   0         0  2017
504  4510         1                   1                   0         0  2017
505  4511         1                   1                   0         0  2017
506  4512         1                   1                   0         0  2017
507  4513         1                   1                   0         0  2017
508  4514         0                   0                   0         0  2017
509  4515         0                   1                   0         0  2017
510  4516         1                   1                   0         0  2017
511  4517         1                   1                   0         0  2017
512  4518         0                   0                   0         0  2017
513  4519         1                   1                   0         0  2017
514  4520         1                   1                   0         0  2017
515  4521         0                   0                   0         0  2017
516  4522         1                   0                   0         0  2017
517  4523         1                   0                   1         0  2017
518  4524         1                   1                   0         0  2017
519  4525         0                   0                   0         0  2017

[520 rows x 6 columns]

In [10]:
data_out.duplicated().sum()

0

In [11]:
data_out.drop_duplicates(inplace=True)

In [12]:
data_out = data_out.drop('年报年份', axis=1)
data_out.isna().sum()

企业编号                  0
是否有网站或网点              0
企业是否有投资信息或购买其他公司股权    0
有限责任公司本年度是否发生股东股权转    0
是否提供对外担保              0
dtype: int64

In [16]:
data_out.fillna(data_out.mode().iloc[0], inplace=True)
data_out.isna().sum()

企业编号                  0
是否有网站或网点              0
企业是否有投资信息或购买其他公司股权    0
有限责任公司本年度是否发生股东股权转    0
是否提供对外担保              0
dtype: int64

In [13]:
data_out.to_excel('年报-企业基本信息_特征.xlsx', index=False)